export type StudentInternship = {
  id?: number,
  specifications: boolean,
  visitForm: boolean,
  evaluationForm: boolean,
  webSurvey: boolean,
  reportSent: boolean,
  oralPresentation: boolean,
  visitPlanned: boolean,
  visitDone: boolean
  technicalGrade: number,
  communicationGrade: number,
  mission: string,
  startingDate: string,
  endingDate: string,
  companyName: string,
  companyTutorName: string,
  companyAddress: string,
  comment: string,
};