export type Student = {
  id: string,
  group: string,
  lastName: string,
  firstName: string,
  specifications: boolean,
  visitForm: boolean,
  evaluationForm: boolean,
  webSurvey: boolean,
  reportSent: boolean,
  oralPresentation: boolean,
  visitPlanned: boolean,
  visitDone: boolean,
  startDate: number,
  endDate: number,
  company: string,
  tutor: string,
  address: string,
  technicalGrade: number,
  communicationGrade: number,
};