export const data = [
  {
    id: '1',
    group: 'M2',
    lastName: 'LI',
    firstName: 'William',
    specifications: true,
    visitForm: true,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: '12',
    communicationGrade: '13',
  },
];
