import { Student } from "../types/Student";

export const data: Array<Student> = [
  {
    id: '1',
    group: 'M2',
    lastName: 'LI',
    firstName: 'William',
    specifications: false,
    visitForm: true,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: 12,
    communicationGrade: 13,
  },
  {
    id: '1',
    group: 'M2',
    lastName: 'LI',
    firstName: 'William',
    specifications: true,
    visitForm: true,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: 12,
    communicationGrade: 13,
  },
  {
    id: '1',
    group: 'M2',
    lastName: 'LI',
    firstName: 'William',
    specifications: true,
    visitForm: true,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: 12,
    communicationGrade: 13,
  },
  {
    id: '1',
    group: 'M2',
    lastName: 'LI',
    firstName: 'William',
    specifications: true,
    visitForm: true,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: 12,
    communicationGrade: 13,
  },
  {
    id: '1',
    group: 'M2',
    lastName: 'LI',
    firstName: 'William',
    specifications: false,
    visitForm: false,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: 12,
    communicationGrade: 13,
  },
];
