import {Student} from "../types/Student";
/*
export const data: Array<Student> = [
  {
    id: '1',
    promotion: 'M2',
    lastname: 'LI',
    firstname: 'William',
    specifications: false,
    visitForm: true,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: 12,
    communicationGrade: 13,
  },
  {
    id: '1',
    promotion: 'M2',
    lastname: 'LI',
    firstname: 'William',
    specifications: true,
    visitForm: true,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: 12,
    communicationGrade: 13,
  },
  {
    id: '1',
    promotion: 'M2',
    lastname: 'LI',
    firstname: 'William',
    specifications: true,
    visitForm: true,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: 12,
    communicationGrade: 13,
  },
  {
    id: '1',
    promotion: 'M2',
    lastname: 'LI',
    firstname: 'William',
    specifications: true,
    visitForm: true,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: 12,
    communicationGrade: 13,
  },
  {
    id: '1',
    promotion: 'M2',
    lastname: 'LI',
    firstname: 'William',
    specifications: false,
    visitForm: false,
    evaluationForm: true,
    webSurvey: true,
    reportSent: true,
    oralPresentation: true,
    visitPlanned: true,
    visitDone: true,
    startDate: 1678628403,
    endDate: 1678628403,
    company: 'EFREI',
    tutor: 'Jacques Augustin',
    address: '32 Avenue de la Republique',
    technicalGrade: 12,
    communicationGrade: 13,
  },
];
*/
export const data: Student[] = [
  {
    "id": 1,
    "firstname": "pierre",
    "lastname": "hevert",
    "email": "pierre.hevert@gmail.com",
    "promotion": "M2",
    "studentInternship": [
      {
        "id": 1,

        "mission": "servir café",
        "companyName": "accent",
        "companyTutorName": "bernard",
        "startingDate": "2020-02-02",
        "endingDate": "2020-05-05",
        "comment": "Stage M2",
        "companyAddress": "56 rue du blabla",
        "technicalGrade": 10,
        "specifications": false,
        "visitForm": false,
        "evaluationForm": true,
        "webSurvey": true,
        "reportSent": true,
        "oralPresentation": true,
        "visitPlanned": true,
        "visitDone": true,
        "communicationGrade": 11
      },
      {
        "id": 2,
        "mission": "Conception d'une platform",
        "companyName": "SOS",
        "companyTutorName": "henry",
        "startingDate": "2021-02-02",
        "endingDate": "2021-05-05",
        "comment": "Stage M2",
        "companyAddress": "56 rue du blabla",
        "technicalGrade": 10,
        "specifications": false,
        "visitForm": false,
        "evaluationForm": true,
        "webSurvey": true,
        "reportSent": true,
        "oralPresentation": true,
        "visitPlanned": true,
        "visitDone": true,
        "communicationGrade": 11
      }
    ]
  },
  {
    "id": 3,
    "firstname": "pande",
    "lastname": "renard",
    "email": "pande.renard@gmail.com",
    "promotion": "M2",
    "studentInternship": [
      {
        "id": 1,
        "mission": "servir café",
        "companyName": "accent",
        "companyTutorName": "bernard",
        "startingDate": "2020-02-02",
        "endingDate": "2020-05-05",
        "comment": "Stage M2",
        "companyAddress": "56 rue du blabla",
        "technicalGrade": 10,
        "specifications": false,
        "visitForm": false,
        "evaluationForm": true,
        "webSurvey": true,
        "reportSent": true,
        "oralPresentation": false,
        "visitPlanned": true,
        "visitDone": true,
        "communicationGrade": 11
      }
    ]
  }
];
